# --- A1 simulator: STD 1.1.3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1-sim-std
  namespace: istio-nonrtric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1-sim-std
  template:
    metadata:
      labels:
        app: a1-sim-std
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: a1-sim
          image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: A1_VERSION       # set the variant here
              value: STD_1.1.3       # for a1-sim-std
            - name: ALLOW_HTTP
              value: "true"
            - name: REMOTE_HOSTS_LOGGING
              value: "1"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: a1-sim-std
  namespace: istio-nonrtric
spec:
  selector:
    app: a1-sim-std
  ports:
    - name: http
      port: 3000
      targetPort: 3000

# --- A1 simulator: STD 2.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1-sim-std-v2
  namespace: istio-nonrtric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1-sim-std-v2
  template:
    metadata:
      labels:
        app: a1-sim-std-v2

      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: a1-sim
          image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.2.0
          imagePullPolicy: IfNotPresent
          env: 
          - name: A1_VERSION       # set the variant here
            value: STD_2.0.0      # for a1-sim-std
          - name: ALLOW_HTTP
            value: "true"
          - name: REMOTE_HOSTS_LOGGING
            value: "1"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: a1-sim-std-v2
  namespace: istio-nonrtric
spec:
  selector:
    app: a1-sim-std-v2
  ports:
    - name: http
      port: 3000
      targetPort: 3000

# --- A1 simulator: OSC 2.1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1-sim-osc
  namespace: istio-nonrtric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a1-sim-osc
  template:
    metadata:
      labels:
        app: a1-sim-osc
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: a1-sim
          image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.2.0
          imagePullPolicy: IfNotPresent
          env:
          - name: A1_VERSION       # set the variant here
            value: OSC_2.1.0      # for a1-sim-std
          - name: ALLOW_HTTP
            value: "true"
          - name: REMOTE_HOSTS_LOGGING
            value: "1"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: a1-sim-osc
  namespace: istio-nonrtric
spec:
  selector:
    app: a1-sim-osc
  ports:
    - name: http
      port: 3000
      targetPort: 3000

# --- A1 Policy Management Service (PMS)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-agent
  namespace: istio-nonrtric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-agent
  template:
    metadata:
      labels:
        app: policy-agent
    spec:
      containers:
        - name: pms
          image: nexus3.o-ran-sc.org:10002/o-ran-sc/nonrtric-a1-policy-management-service:2.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: pms-config
              mountPath: /opt/app/policy-agent/data/application_configuration.json
              subPath: application_configuration.json
      volumes:
        - name: pms-config
          configMap:
            name: pms-config
---
apiVersion: v1
kind: Service
metadata:
  name: policy-agent
  namespace: istio-nonrtric
spec:
  selector:
    app: policy-agent
  ports:
    - name: http
      port: 8081
      targetPort: 8081

# --- Non-RT RIC Gateway (service-exposure)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonrtric-gateway
  namespace: istio-nonrtric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonrtric-gateway
  template:
    metadata:
      labels:
        app: nonrtric-gateway
    spec:
      containers:
        - name: gateway
          image: nexus3.o-ran-sc.org:10002/o-ran-sc/nonrtric-gateway:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/config/
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gateway-config
              mountPath: /config/application-nonrtricgateway.yaml
              subPath: application-nonrtricgateway.yaml
      volumes:
        - name: gateway-config
          configMap:
            name: gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: nonrtric-gateway
  namespace: istio-nonrtric
spec:
  selector:
    app: nonrtric-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
